#!/bin/sh

if [ "$SKIP_SIMPLE_GIT_HOOKS" = "1" ]; then
    echo "[INFO] SKIP_SIMPLE_GIT_HOOKS is set to 1, skipping hook."
    exit 0
fi

if [ -f "$SIMPLE_GIT_HOOKS_RC" ]; then
    . "$SIMPLE_GIT_HOOKS_RC"
fi

npx @biomejs/biome check --staged --write --no-errors-on-unmatched && staged=$(git diff --name-only --cached --diff-filter=ACMR) && { [ -z "$staged" ] || printf '%s\n' "$staged" | while IFS= read -r file; do [ -z "$file" ] || git add -- "$file"; done; }